rvm: '2.5.0'

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -c 'CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(60), username VARCHAR(60), email VARCHAR(60), password VARCHAR(140));' -U postgres
  - psql -c 'CREATE TABLE peeps(id SERIAL PRIMARY KEY, text VARCHAR(240), tstz TIMESTAMPTZ, user_id INTEGER REFERENCES users (id));' -U postgres
